pgdb:
  image: postgres:9.4.4
  environment:
    - POSTGRES_DB=jodd-test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=root!
    - LC_ALL=C.UTF-8
  ports:
     - "5432:5432"
mydb:
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=root!
  ports:
    - "3306:3306"