// Copyright (c) 2003-2011, Jodd Team (jodd.org). All Rights Reserved.

package jodd.util.testdata;

public class JavaBean {

	private int one;

	private boolean two;

	private String three;

	private String f;

	private byte G;

	private String URL;

	private long BIGsmall;

	// ---------------------------------------------------------------- autogenerated

	public int getOne() {
		return one;
	}

	public void setOne(int one) {
		this.one = one;
	}

	public boolean isTwo() {
		return two;
	}

	public void setTwo(boolean two) {
		this.two = two;
	}

	public String getThree() {
		return three;
	}

	public void setThree(String three) {
		this.three = three;
	}

	public String getF() {
		return f;
	}

	public void setF(String f) {
		this.f = f;
	}

	public byte getG() {
		return G;
	}

	public void setG(byte g) {
		G = g;
	}

	public String getURL() {
		return URL;
	}

	public void setURL(String URL) {
		this.URL = URL;
	}

	public long getBIGsmall() {
		return BIGsmall;
	}

	public void setBIGsmall(long BIGsmall) {
		this.BIGsmall = BIGsmall;
	}
}
